import React, { useState, useEffect } from "react";
import TopBar from "./Topbar";
import Head from "next/head";
import Footer from "./Footer";
import { motion } from "framer-motion";
import Loader from "./Loader";

export default function Layout({ children }) {
  const [isLoading, setIsLoading] = useState(true);

  const variants = {
    hidden: { opacity: 0, x: -100 },
    visible: { opacity: 1, x: 0, transition: { duration: 1 } },
  };

  useEffect(() => {
    // Simulate loading delay
    setTimeout(() => {
      setIsLoading(false);
    }, 3000);
  }, []);

  return (
    <>
      <Head>
        <title>Banana88 Trans</title>
        <meta name="description" content="Generated by Banana88 Trans" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoading ? (
        <Loader />
      ) : (
        <motion.div variants={variants} initial="hidden" animate="visible">
          <TopBar />
          {children}
          <Footer />
        </motion.div>
      )}
    </>
  );
}
